## ACT — the retro showcase map, built in front of the viewer.
##
## WHAT THIS ACT IS NOT: an invented blockout. Every structural piece is placed
## with the ordinary creation flow AT THE FOOTPRINT THE SHIPPED MAP PUTS IT AT.
## That map (`project/test_scenes/test_map_showcase.tscn`) is generated by
## TestMapShowcaseBuilder, the AABBs in `REAL` below were probed out of it, and
## each beat asserts the piece it just built against its number — so the
## courtyard the PSP runs in the next act is recognisably THIS scene, not a
## lookalike. Materials come from the same builder too (tiles / wet tiles /
## the water materials), so the map that reaches the device wears exactly what
## the device shows.
##
## The pieces the creation flow has no tool for — the blended water sheets'
## scroll speeds, the foliage billboards, the particle emitters, the lights —
## are added through the builder's own helpers while the camera is elsewhere,
## and the beat AFTER them is framed on the result.
@tool
extends RefCounted

var director: ShowcaseDirector
var d: ShowcaseDirector
var root: Node
var pieces: Dictionary = {}
var floor_node: PBMesh = null

const TEX_DIR := "res://addons/poibuilder/materials/textures/"
const TILES := TEX_DIR + "tiles_light_4x4.png"
const BRICK := TEX_DIR + "brick_path_4x4.png"
const STAMP := TEX_DIR + "stamp_hello_world.png"
const WATER_SHEET := TEX_DIR + "waterfall_sheet.png"
const WATER_CORE := TEX_DIR + "waterfall_core.png"
const WATER_POOL := TEX_DIR + "water_pool.png"
const WATER_FOAM := TEX_DIR + "water_foam.png"
const WATER_SPRAY := TEX_DIR + "water_spray.png"
const TREE_PINE := TEX_DIR + "tree_pine.png"
const TREE_OAK := TEX_DIR + "tree_oak.png"
const BUSH := TEX_DIR + "bush_foliage.png"
const FLOWERS := TEX_DIR + "flower_patch.png"
const FLAME := TEX_DIR + "particle_flame.png"
const GLOW := TEX_DIR + "particle_glow.png"
const SMOKE := TEX_DIR + "particle_smoke.png"

## The shipped map's own world-space AABBs (min, max), probed from
## TestMapShowcaseBuilder.build_showcase_scene(). A beat that drifts from these
## is building a different courtyard.
const REAL := {
	"CourtFloor": [Vector3(-6.0, -0.5, -6.0), Vector3(6.0, 0.0, 6.0)],
	"Archway": [Vector3(-2.0, 0.0, -6.0), Vector3(2.0, 4.0, -5.0)],
	"GrandStairs": [Vector3(-5.75, 0.0, -2.0), Vector3(-3.25, 3.0, 2.0)],
	"Balcony": [Vector3(-6.0, 2.8, -6.0), Vector3(-3.0, 3.2, -2.0)],
	"PillarA": [Vector3(-3.6, 0.0, -4.35), Vector3(-2.8, 3.0, -3.65)],
	"PillarB": [Vector3(-5.9, 0.0, -4.35), Vector3(-5.1, 3.0, -3.65)],
	"RampEast": [Vector3(3.5, 0.0, -1.0), Vector3(5.5, 2.0, 3.0)],
	"FallWall": [Vector3(2.5, 0.0, -5.6), Vector3(6.5, 5.0, -5.0)],
	"FallSheet": [Vector3(3.5, 0.1, -4.94), Vector3(5.5, 4.3, -4.94)],
	"FallCore": [Vector3(3.8, 0.1, -4.86), Vector3(4.7, 4.1, -4.86)],
	"FallPool": [Vector3(2.7, 0.04, -5.0), Vector3(6.3, 0.04, -1.8)],
	"FallFoam": [Vector3(3.1, 0.06, -5.0), Vector3(5.9, 0.06, -3.4)],
}

func run(dr: ShowcaseDirector) -> void:
	d = dr
	d.fill_scale = 1.35
	root = EditorInterface.get_edited_scene_root()
	ShowcaseUtil.env(d.plugin, "day")
	ShowcaseUtil.grade_light(root)
	ShowcaseUtil.fresh_grid(d.plugin)
	# No bench and no walls: the courtyard IS the scene, which is why the grid
	# has to go once the floor exists (a surface at the grid's own elevation
	# z-fights with it).
	await d.frames(16)
	await d.shot("map/floor", _floor)
	await d.shot("map/arch", _arch)
	await d.shot("map/pillars", _pillars)
	await d.shot("map/stairs", _stairs)
	await d.shot("map/waterfall", _waterfall)
	await d.shot("map/paint", _paint)
	await d.shot("map/particles", _particles)
	await d.shot("map/export", _export)
	await d.shot("map/night", _night)
	d.snapshot_regions()

# -----------------------------------------------------------------------------
# helpers
# -----------------------------------------------------------------------------

func _clear() -> void:
	EditorInterface.get_selection().clear()
	for c in root.get_children():
		root.remove_child(c)
		c.free()
	pieces.clear()
	floor_node = null

## Camera framing for a footprint on the floor, from a chosen corner.
func _view(box: AABB, fill := 0.62, az := 36.0, elev := 26.0) -> Dictionary:
	return d.framing(box, fill, az, elev)

## The working area (in world space) around a footprint, expanded so the piece
## being built is never half out of frame.
func _work(a: Vector3, b: Vector3, height: float) -> AABB:
	var lo := a.min(b) - Vector3(2.2, 0.0, 2.2)
	var span := (b - a).abs() + Vector3(4.4, height + 2.2, 4.4)
	lo.y = 0.0
	return AABB(lo, span)

## Drag-creates a shape on the floor (or on whatever surface the start point
## lands on) and drives the height stage to `height` metres ALONG THE NORMAL.
## `setup` runs while the shape's parameter modal is open; `mat` dresses the
## finished node. Returns the created node.
func _place(shape_id: StringName, name_hint: String, a: Vector3, b: Vector3,
		height: float, mat: Material = null, setup: Callable = Callable(),
		snap_height := true, az := 36.0, elev := 26.0, snap := true) -> PBMesh:
	var before := ShowcaseUtil.names_of(root, "Shape_")
	# `snap` false draws the piece at the pointer's exact position instead of the
	# grid's: the shipped map's own coordinates are not all grid multiples (its
	# waterfall wall spans 2.5..6.5, its stairs -5.75..-3.25), and snapping
	# quantised them onto the step — a 4 m wall came out 3.8 m, a 0.2 m sliver
	# away from the map the video is supposed to be building.
	var grid_was: bool = d.plugin.grid.enabled
	# Explicit, not inherited: the piece's own flag decides (a leftover "snap
	# off" from a previous beat or session must not silently change the drag).
	d.plugin.grid.enabled = snap
	# `az`/`elev` matter: the base drag lands on the FIRST surface its ray hits,
	# so a piece drawn under an overhang has to be approached from low down —
	# from above, the overhang is what the drag would land on (this is how a
	# pillar once came out lying on the balcony instead of standing on the floor).
	await d.frame_box_to(_work(a, b, height), az, elev, 0.55, 24)
	await d.arm_shape(shape_id)
	await d.drag(d.w2s(a), d.w2s(b), 26)
	# The height stage is mouse-driven: the pointer walks along the normal and
	# the plugin reads its position back, so the value is asserted, not hoped for.
	# Snapping quantises the height to the grid's 0.2 m step, which is right for
	# everything that stands ON the floor and wrong for the floor itself (its
	# walking surface has to land exactly at y = 0).
	if not snap_height:
		d.plugin.grid.enabled = false
	var got: float = await d.height_drag_to(height)
	if not snap_height:
		d.plugin.grid.enabled = grid_was
	d.check(absf(got - height) < 0.05, "%s height drag reached %.2f m (%.2f)" % [name_hint, height, got])
	if absf(got) < 0.001 and absf(height) > 0.001:
		# The base drag never started (the press missed every surface): abort the
		# session so the NEXT piece does not inherit it, and say so.
		await d.off(func():
			d.plugin.shape_creator.reset())
		d.check(false, "%s: the base drag never started" % name_hint)
	await d.click()
	await d.frames(8)
	if d.plugin.tool_overlay.params_open:
		if setup.is_valid():
			await setup.call()
		await d.overlay_button("ApplyParams", 12)
	d.plugin.grid.enabled = grid_was
	var after := ShowcaseUtil.names_of(root, "Shape_")
	for n in after:
		if not before.has(n):
			n.name = name_hint
			if mat != null:
				ShowcaseUtil.dress_material(n, mat)
			pieces[name_hint] = n
			return n
	d.check(false, "%s was created" % name_hint)
	return null

## The world-space AABB of a built piece.
func _box(node: Node3D) -> AABB:
	var mi := node as MeshInstance3D
	if mi == null or mi.mesh == null:
		return AABB()
	return mi.global_transform * mi.get_aabb()

## Asserts a piece against the shipped map's own numbers — the whole point of
## this act is that the video's courtyard and the device's are the same one.
func _matches(name: String, node: Node3D, tol := 0.12) -> void:
	if node == null:
		d.check(false, "%s exists" % name)
		return
	var want: Array = REAL[name]
	var box := _box(node)
	var ok: bool = box.position.distance_to(want[0]) <= tol \
		and (box.position + box.size).distance_to(want[1]) <= tol
	d.check(ok, "%s matches the shipped map (got %s..%s, want %s..%s)" % [
		name, str(box.position.snappedf(0.01)), str((box.position + box.size).snappedf(0.01)),
		str(want[0]), str(want[1])])

## Asserts a FLAT water layer against the shipped map's PLAN (x/z) and that it
## floats clear of the floor it was drawn on.
##
## The lift is the one number that is deliberately NOT the map's: the map's pool
## and foam sit 4 and 6 cm above the floor, two centimetres apart from each
## other, and in an editing viewport at a grazing angle that is a z-fight (the
## striped band across the wet stone in the first cuts of this act). The device
## resolves them by draw order; the editor does not. Everything else — where the
## layer sits in plan, what it is made of, how it scrolls — is the map's own.
func _matches_footprint(name: String, node: Node3D, clearance := 0.03) -> void:
	if node == null:
		d.check(false, "%s exists" % name)
		return
	var want: Array = REAL[name]
	var box := _box(node)
	var want_hi: Vector3 = want[1]
	var ok: bool = absf(box.position.x - want[0].x) <= 0.06 \
		and absf(box.position.z - want[0].z) <= 0.06 \
		and absf(box.position.x + box.size.x - want_hi.x) <= 0.06 \
		and absf(box.position.z + box.size.z - want_hi.z) <= 0.06
	d.check(ok, "%s covers the shipped map's footprint (got x %.2f..%.2f z %.2f..%.2f, want x %.2f..%.2f z %.2f..%.2f)" % [
		name, box.position.x, box.position.x + box.size.x, box.position.z, box.position.z + box.size.z,
		want[0].x, want_hi.x, want[0].z, want_hi.z])
	d.check(box.position.y >= clearance,
		"%s floats %.2f m above the floor it was drawn on (no coplanar fight)" % [name, box.position.y])

func _keep(name: String, node: PBMesh) -> void:
	pieces[name] = node

# -----------------------------------------------------------------------------
# beats
# -----------------------------------------------------------------------------

## The courtyard floor: a 12x12 slab whose WALKING SURFACE lands at y = 0, which
## is the grid plane — so the height drag goes DOWN (negative) and the grid is
## switched off the moment the slab exists, or the two z-fight.
func _floor() -> void:
	await d.off(func(): _clear())
	var f := _view(AABB(Vector3(-6.0, 0.0, -6.0), Vector3(12.0, 4.0, 12.0)), 0.86, 40.0, 32.0)
	d.cam_at_polar(f["center"], f["az"], f["elev"], f["dist"], f["aim"])
	await d.frames(6)
	# Nothing is in the scene yet, so the base drag lands on the grid plane —
	# exactly the ProBuilder "drag on the grid" case.
	await d.grid_show(true)
	var slab := await _place(&"cube", "CourtFloor", Vector3(-6.0, 0.0, -6.0), Vector3(6.0, 0.0, 6.0),
		-0.5, PBMeshData.load_material_or_texture(TILES), Callable(), false)
	if slab != null:
		floor_node = slab
		EditorInterface.get_selection().add_node(slab)
	await d.grid_show(false)
	_matches("CourtFloor", slab)
	await d.cam_swing(f["center"], 40.0, 30.0, 32.0, 40.0, f["dist"], 34, 1, f["aim"])

## The north portal: a free-standing arched doorway, built and arched from its
## own parameter modal, framed so the arch itself is the subject.
func _arch() -> void:
	var a := Vector3(-2.0, 0.0, -6.0)
	var b := Vector3(2.0, 0.0, -5.0)
	var door := await _place(&"door", "Archway", a, b, 4.0,
		TestMapShowcaseBuilder.tiles_material(),
		func():
			await d.overlay_param("opening_height", 2.8, 8)
			await d.overlay_param("leg_width", 0.8, 8)
			await d.overlay_param("arch_segments", 8, 8)
			await d.overlay_param_check("arched", true, 10))
	_keep("Archway", door)
	_matches("Archway", door)
	if door != null:
		# The doorway wears the shipped map's own tile material — asserted, so a
		# material regression cannot quietly change the map's look.
		var mi := door as MeshInstance3D
		var sm := mi.mesh.surface_get_material(0) as StandardMaterial3D
		d.check(sm != null and sm.albedo_texture == load(TILES),
			"the doorway wears the shipped map's tile material")
		# Two reads of the arch. A low 3/4 from the courtyard shows the curve,
		# the jambs and the opening...
		var f := d.framing_node(door, 0.55, 26.0, 12.0)
		await d.cam_at_polar(f["center"], f["az"], f["elev"], f["dist"], f["aim"])
		await d.frames(8)
		# ...then the far side of the doorway, where the arch frames the lit
		# courtyard — which is what a doorway is for. The camera is MOVED there
		# off-camera: a dolly would cross the door's own plane and flash a couple
		# of frames of solid tile.
		await d.off(func():
			d.cam_look_at(Vector3(0.0, 1.9, -11.4), Vector3(0.0, 1.3, 4.0)))
		await d.frames(8)
		# Square to the arch on purpose (swinging off-axis aims the view at the
		# door's solid band above the opening) and it stops well short of the
		# doorway: walk any closer and the opening overflows the frame, so the
		# arch stops reading as an arch.
		await d.cam_move(Vector3(0.0, 1.9, -8.8), Vector3(0.0, 1.3, 4.0), 92, 1)
		await d.frames(6)

## The terrace: stairs built across the courtyard's west side (rising north)
## and the balcony platform, drawn on the GRID LIFTED to the balcony's own
## elevation so the slab lands in the air where the shipped map has it.
func _stairs() -> void:
	# stairs: 2.5 wide, 4 deep, 3 high, 8 steps, dragged northward so the run
	# climbs toward -Z like the shipped map's (it is rotated 180 degrees there).
	var stairs := await _place(&"stair", "GrandStairs", Vector3(-5.75, 0.0, 2.0), Vector3(-3.25, 0.0, -2.0),
		3.0, TestMapShowcaseBuilder.tiles_material(),
		func(): await d.overlay_param("steps", 8, 10), true, 36.0, 26.0, false)
	_keep("GrandStairs", stairs)
	_matches("GrandStairs", stairs)
	# balcony: 3 x 0.4 x 4 slab at y 2.8..3.2 — created on the grid raised to
	# 2.8 m (the "draw on grid" workflow), then the grid is put back.
	await d.off(func():
		d.plugin.grid.origin.y = 2.8
		d.plugin.grid.draw_on_grid = true)
	var balcony := await _place(&"cube", "Balcony", Vector3(-6.0, 2.8, -6.0), Vector3(-3.0, 2.8, -2.0),
		0.4, TestMapShowcaseBuilder.tiles_material())
	await d.off(func():
		d.plugin.grid.draw_on_grid = false
		d.plugin.grid.origin.y = 0.0)
	_keep("Balcony", balcony)
	_matches("Balcony", balcony)
	if stairs != null:
		var f := d.framing_node(stairs, 0.72, 62.0, 14.0)
		await d.cam_at_polar(f["center"], f["az"], f["elev"], f["dist"], f["aim"])
		await d.cam_swing(f["center"], 62.0, 44.0, 14.0, 26.0, float(f["dist"]) * 0.92, 40, 1, f["aim"])

## The west colonnade (two hexagonal pillars) and the east ramp.
func _pillars() -> void:
	var a := await _place(&"cylinder", "PillarA", Vector3(-3.6, 0.0, -4.35), Vector3(-2.8, 0.0, -3.65),
		3.0, TestMapShowcaseBuilder.tiles_material(),
		func(): await d.overlay_param("sides", 6, 10))
	var b := await _place(&"cylinder", "PillarB", Vector3(-5.9, 0.0, -4.35), Vector3(-5.1, 0.0, -3.65),
		3.0, TestMapShowcaseBuilder.tiles_material(),
		func(): await d.overlay_param("sides", 6, 10), true, 24.0, 11.0)
	_keep("PillarA", a)
	_keep("PillarB", b)
	_matches("PillarA", a)
	_matches("PillarB", b)
	var ramp := await _place(&"prism", "RampEast", Vector3(3.5, 0.0, -1.0), Vector3(5.5, 0.0, 3.0),
		2.0, TestMapShowcaseBuilder.tiles_material(), Callable(), true, 36.0, 26.0, false)
	_keep("RampEast", ramp)
	_matches("RampEast", ramp)
	# Close on the colonnade, then out to the map so far: the courtyard reads as
	# a place at this point (doorway, stairs, balcony, pillars, ramp all in one).
	var f := d.framing(AABB(Vector3(-6.2, 0.0, -4.8), Vector3(4.2, 3.6, 2.4)), 0.5, 30.0, 14.0)
	await d.cam_at_polar(f["center"], f["az"], f["elev"], f["dist"], f["aim"])
	await d.frames(6)
	var wide := _view(AABB(Vector3(-6.5, 0.0, -6.5), Vector3(13.0, 5.0, 13.0)), 0.62, 40.0, 20.0)
	var pose: Array = d.polar_pose(wide["center"], wide["az"], wide["elev"], wide["dist"], wide["aim"])
	await d.cam_move(pose[0], pose[1], 60, 1)
	await d.cam_swing(wide["center"], 40.0, 52.0, 20.0, 28.0, float(wide["dist"]), 40, 1, wide["aim"])

## The waterfall: a wall panel, then the water itself as three planes drawn
## against it (the sheet + core hang on the wall, the pool lies on the floor).
## Each sheet is a plane created ON the wall face and offset along its normal —
## the shape the plane tool exists for.
func _waterfall() -> void:
	# the wall panel: 4 wide x 5 high x 0.6 deep, standing on the floor
	var wall_a := Vector3(2.5, 0.0, -5.6)
	var wall_b := Vector3(6.5, 0.0, -5.0)
	var wall := await _place(&"cube", "FallWall", wall_a, wall_b, 5.0,
		TestMapShowcaseBuilder.wet_tiles_material(), Callable(), true, 36.0, 26.0, false)
	_keep("FallWall", wall)
	_matches("FallWall", wall, 0.06)
	# the two standing sheets, drawn against the wall's courtyard-facing side
	var sheet := await _plane("FallSheet", Vector3(3.5, 0.1, -5.0), Vector3(5.5, 4.3, -5.0), 0.06,
		TestMapShowcaseBuilder.water_material("FallSheet_Mat", WATER_SHEET, Vector2(0.04, -0.75), true),
		Vector2(0.6, 0.35))
	_keep("FallSheet", sheet)
	_matches("FallSheet", sheet, 0.06)
	# The core is drawn ON THE SHEET it sits in front of (z = -4.94), not on the
	# wall: the press ray lands on whatever surface is first under the cursor, so
	# aiming at the wall would put the rect 6 cm behind where the cursor is and
	# shift the whole footprint. Its 8 cm stand-off lands it exactly on the
	# shipped map's -4.86.
	var core := await _plane("FallCore", Vector3(3.8, 0.1, -4.94), Vector3(4.7, 4.1, -4.94), 0.08,
		TestMapShowcaseBuilder.water_material("FallCore_Mat", WATER_CORE, Vector2(0.0, -1.15), true),
		Vector2(1.2, 0.5))
	_keep("FallCore", core)
	_matches("FallCore", core, 0.06)
	# The pool on the floor, spreading away from the wall. Both floor layers are
	# dragged from their NEAR corner: the press ray stops at whatever surface is
	# first under the cursor, and the far corner sits exactly on the wall's base
	# plane — a press there hits the WALL, and the pool comes out vertical (the
	# foam did, 0.8 m below the floor). A rect is direction-agnostic, so starting
	# from the near corner changes nothing but which surface the ray lands on.
	var pool := await _plane("FallPool", Vector3(6.3, 0.0, -1.8), Vector3(2.7, 0.0, -5.0), 0.06,
		TestMapShowcaseBuilder.water_material("FallPool_Mat", WATER_POOL, Vector2(0.02, -0.03), true),
		Vector2(0.55, 0.55))
	_keep("FallPool", pool)
	# The foam sits ON the pool and they overlap in plan: 2 cm apart they fought
	# for depth on camera, which is what the striped band across the wet floor
	# was. 12 cm is the smallest separation that stays clear at grazing angles.
	# Drawn on the POOL (y = 0.06), the surface it actually rests on — aiming at
	# the floor under it shifted the rect ~0.2 m south, because the press ray
	# stops at the pool first. 12 cm of stand-off keeps the two layers clear.
	var foam := await _plane("FallFoam", Vector3(5.9, 0.06, -3.4), Vector3(3.1, 0.06, -5.0), 0.12,
		TestMapShowcaseBuilder.water_material("FallFoam_Mat", WATER_FOAM, Vector2(0.0, -0.30), true),
		Vector2(0.5, 0.9))
	_keep("FallFoam", foam)
	_matches_footprint("FallPool", pool)
	_matches_footprint("FallFoam", foam)
	# The rest of the shipped composition — the spray billboard, the mist and
	# flame emitters, the foliage, the lights — is added while the camera is
	# still on the wall, and the beats after this one are framed on it.
	await d.off(_dress_scene)
	# Stand back and read the whole composition: the wall panel, both scrolling
	# sheets on it, and the pool spreading over the floor in front.
	var f := d.framing(AABB(Vector3(2.2, 0.0, -6.2), Vector3(5.2, 5.4, 5.6)), 0.52, 30.0, 15.0)
	await d.cam_at_polar(f["center"], f["az"], f["elev"], f["dist"], f["aim"])
	await d.frames(8)
	await d.cam_swing(f["center"], 30.0, 46.0, 15.0, 24.0, float(f["dist"]) * 0.94, 54, 1, f["aim"])

## A stand-off plane: a base drag on `a`..`b` (the surface it is drawn on),
## then the offset stage lifts it along the surface normal by `offset`.
func _plane(name_hint: String, a: Vector3, b: Vector3, offset: float,
		mat: Material, uv_scale := Vector2.ONE) -> PBMesh:
	var before := ShowcaseUtil.names_of(root, "Shape_")
	var center := (a + b) * 0.5
	var f := d.framing(AABB(a.min(b) - Vector3(0.6, 0.6, 0.6), (b - a).abs() + Vector3(1.2, 1.2, 1.2)), 0.6, 30.0, 18.0)
	await d.frame_box_to(AABB(a.min(b) - Vector3(0.8, 0.8, 0.8), (b - a).abs() + Vector3(1.6, 1.6, 1.6)),
		30.0, 18.0, 0.6, 24)
	# These sheets are SMALLER than the grid's step (2.0 x 4.2, 0.9 x 4.0,
	# 3.6 x 3.2, 2.8 x 1.6) and stand off their surface by centimetres, so
	# snapping quantises both away: a 4.2 m drag became 4.4, and the 6 cm
	# stand-off became 0 — the sheet lying IN the wall and the pool IN the
	# floor, which is where the striped z-fighting across the wet stone came
	# from. The shipped map's own numbers are the target, so snapping is off
	# for the whole plane flow (the same way the courtyard floor turns it off
	# for its negative height).
	var snap_was: bool = d.plugin.grid.enabled
	d.plugin.grid.enabled = false
	await d.arm_shape(&"plane")
	await d.drag(d.w2s(a), d.w2s(b), 26)
	# OFFSET stage: the sheet rides out along the surface normal (there is no
	# third dimension to drag — see PBShapeParams.height_drags_offset). The
	# normal is the one the creator captured from the face that was drawn on,
	# and the value is CLOSED-LOOP: the plugin reads the pointer's position back
	# along that normal, so the pointer has to be walked there and re-read until
	# it agrees — gliding to `centre + normal * offset` and clicking, which this
	# beat used to do, landed the sheet 2 cm off the wall instead of 6.
	var got: float = await d.height_drag_to(offset)
	d.check(absf(got - offset) <= 0.03, "%s stand-off reached %.2f m (%.2f)" % [name_hint, got, offset])
	await d.click()
	await d.frames(8)
	if d.plugin.tool_overlay.params_open:
		await d.overlay_button("ApplyParams", 12)
	d.plugin.grid.enabled = snap_was
	var after := ShowcaseUtil.names_of(root, "Shape_")
	for n in after:
		if not before.has(n):
			n.name = name_hint
			if mat != null:
				ShowcaseUtil.dress_material(n, mat)
			if uv_scale != Vector2.ONE and n.pb_mesh_data.faces.size() > 0:
				n.pb_mesh_data.faces[0].uv_scale = uv_scale
				n.rebuild()
			pieces[name_hint] = n
			return n
	d.check(false, "%s was created" % name_hint)
	return null

## Everything the creation flow has no tool for, added through the shipped
## map's own builder helpers: the spray billboard, the foliage, the emitters
## and the lights. Runs while the camera is on the waterfall wall.
func _dress_scene() -> void:
	var spray := TestMapShowcaseBuilder.create_billboard("WaterfallSpray", WATER_SPRAY,
		Vector2(2.2, 1.5), Vector3(4.5, 0.62, -4.65), false, true)
	PBUv.set_scroll_speed(spray.material_override as Material, Vector2(0.0, 0.35))
	root.add_child(spray)
	var foliage := [
		["Tree_Pine", TREE_PINE, Vector2(2.5, 5.0), Vector3(3.5, 2.5, 4.0)],
		["Tree_Oak", TREE_OAK, Vector2(4.0, 4.5), Vector3(-4.0, 2.25, 4.0)],
		["Bush_Foliage", BUSH, Vector2(1.5, 1.5), Vector3(2.0, 0.75, 3.2)],
		["Wildflowers", FLOWERS, Vector2(1.2, 1.2), Vector3(-2.0, 0.6, 2.0)],
	]
	for entry in foliage:
		root.add_child(TestMapShowcaseBuilder.create_billboard(entry[0], entry[1], entry[2], entry[3], true))
	var brazier := TestMapShowcaseBuilder.create_emitter("Emitter_Brazier", Vector3(-3.2, 3.05, -4.0),
		FLAME, 20, 0.8, 0.9, true, true, 2, 2)
	root.add_child(brazier)
	var embers := TestMapShowcaseBuilder.create_emitter("Emitter_Embers", Vector3(-3.2, 3.05, -4.0),
		GLOW, 12, 1.3, 0.32, true, false)
	var pm := embers.process_material as ParticleProcessMaterial
	pm.initial_velocity_min = 1.1
	pm.initial_velocity_max = 2.0
	pm.spread = 26.0
	root.add_child(embers)
	root.add_child(TestMapShowcaseBuilder.create_emitter("Emitter_Mist", Vector3(4.5, 0.35, -4.7),
		SMOKE, 14, 1.7, 1.3, false, true))
	# the four lights the shipped map carries, so the night preset lands on the
	# same pools of light the device shows
	_add_omni("TorchLight", Vector3(0.0, 2.5, -4.5), Color(1.0, 0.65, 0.3), 2.0, 6.0)
	_add_omni("WaterfallLantern", Vector3(2.9, 2.6, -4.6), Color(0.70, 0.90, 1.0), 2.2, 7.0)
	_add_omni("FoliageFill", Vector3(-0.5, 2.4, 6.4), Color(1.0, 0.94, 0.84), 0.6, 12.0, false)
	var spot := SpotLight3D.new()
	spot.name = "AlcoveSpot"
	spot.transform = Transform3D(Basis.looking_at(Vector3(-1.0, -0.5, 0.0).normalized(), Vector3.UP),
		Vector3(4.0, 3.5, 0.0))
	spot.light_color = Color(0.5, 0.75, 1.0)
	spot.light_energy = 1.5
	spot.spot_angle = 35.0
	root.add_child(spot)
	# The shipped map's spawn marker: the file the device loads carries it.
	var spawn := Marker3D.new()
	spawn.name = "PlayerSpawn"
	spawn.position = Vector3(0.0, 1.6, 4.2)
	root.add_child(spawn)

func _add_omni(name_hint: String, pos: Vector3, color: Color, energy: float, range_m: float,
		shadows := true) -> void:
	var l := OmniLight3D.new()
	l.name = name_hint
	l.position = pos
	l.light_color = color
	l.light_energy = energy
	l.omni_range = range_m
	l.shadow_enabled = shadows
	root.add_child(l)

## The brick path down the middle of the court and the sign decal — the same
## two authoring tools the paint act uses, on the real courtyard floor.
func _paint() -> void:
	var f := _view(AABB(Vector3(-6.0, 0.0, -6.0), Vector3(12.0, 3.0, 12.0)), 0.88, 34.0, 32.0)
	d.cam_at_polar(f["center"], f["az"], f["elev"], f["dist"], f["aim"])
	await d.frames(6)
	if floor_node == null:
		d.check(false, "the courtyard floor is still in the scene")
		return
	d.plugin.editor.active_mesh = floor_node
	EditorInterface.get_selection().clear()
	EditorInterface.get_selection().add_node(floor_node)
	await d.frames(6)
	await d.click_button("materials", 14)
	await d.click_dock_member("_btn_mode_paint", 14)
	var pc = d.plugin.paint_controller
	pc.set_paint_texture_and_update_layer(load(BRICK))
	pc.brush_radius = 1.25
	pc.brush_softness = 0.8
	pc.brush_opacity = 1.0
	await d.frames(6)
	# the floor's top face is at y = 0 now, so the path is painted at y = 0
	var path_pts := [Vector3(0.0, 0.0, 6.2), Vector3(0.0, 0.0, 2.0), Vector3(0.0, 0.0, -2.0),
		Vector3(0.0, 0.0, -5.4)]
	for i in range(path_pts.size() - 1):
		await d.drag(d.w2s(path_pts[i]), d.w2s(path_pts[i + 1]), 16)
	d.check(int(pc.mode) == 1, "brick path painted down the courtyard")
	await d.click_dock_member("_btn_mode_stamp", 14)
	pc.stamp_texture = load(STAMP)
	pc.stamp_scale = 2.6
	pc.stamp_opacity = 1.0
	await d.glide_world_track(Vector3(0.0, 0.0, -3.2), 20)
	await d.frames(6)
	await d.click()
	await d.frames(10)
	var holder := floor_node.get_node_or_null("PBStamps")
	d.check(holder != null and holder.get_child_count() > 0,
		"the sign decal landed on the floor (%d stamps)" % (holder.get_child_count() if holder != null else 0))
	await d.cam_swing(f["center"], 34.0, 18.0, 32.0, 40.0, f["dist"], 34, 1, f["aim"])

## The atmosphere the map carries: the mist at the fall's foot and the brazier
## flames on the pillar (both GPUParticles3D emitters, which is what the retro
## exporters turn into the .pbm's emitter records).
func _particles() -> void:
	# The brazier: flames + embers rising off the pillar top.
	var brazier_box := AABB(Vector3(-3.9, 2.4, -4.6), Vector3(1.6, 2.0, 1.6))
	var f := d.framing(brazier_box, 0.8, 20.0, 14.0)
	d.cam_at_polar(f["center"], f["az"], f["elev"], f["dist"], f["aim"])
	await d.frames(14)
	# Long and slow: a particle effect has to be watched, not passed over.
	await d.cam_swing(f["center"], 20.0, -18.0, 14.0, 7.0, float(f["dist"]) * 0.9, 110, 1, f["aim"])
	# ...then the mist climbing off the waterfall's foot.
	var mist_box := AABB(Vector3(3.5, 0.0, -5.2), Vector3(2.0, 2.8, 2.6))
	await d.frame_box_to(mist_box, 26.0, 12.0, 0.82, 44)
	var g := d.framing(mist_box, 0.82, 26.0, 12.0)
	await d.frames(14)
	await d.cam_swing(g["center"], 26.0, 4.0, 12.0, 18.0, float(g["dist"]), 100, 1, g["aim"])

func _export() -> void:
	var f := _view(AABB(Vector3(-6.0, 0.0, -6.0), Vector3(12.0, 6.0, 12.0)), 0.92, 38.0, 26.0)
	d.cam_at_polar(f["center"], f["az"], f["elev"], f["dist"], f["aim"])
	await d.frames(6)
	var opened := await d.open_export_dialog()
	var dlg = d.plugin._export_dialog
	if opened and dlg != null:
		if dlg._mode_option != null:
			dlg._mode_option.selected = 0
		dlg._txt_path.text = "res://exports/showcase_map.glb"
		await d.frames(24)
		await d.dialog_ok(dlg, 16)
		await d.frames(48)
	await d.cam_swing(f["center"], 38.0, 58.0, 26.0, 34.0, f["dist"], 40, 1, f["aim"])

## One click re-lights the whole courtyard: the toolbar's Env menu swaps the
## environment AND the sun, and the map the device renders in the next act is
## this one at night.
func _night() -> void:
	var f := _view(AABB(Vector3(-6.0, 0.0, -6.0), Vector3(12.0, 6.0, 12.0)), 0.94, 38.0, 20.0)
	d.cam_at_polar(f["center"], f["az"], f["elev"], f["dist"], f["aim"])
	await d.frames(8)
	await d.env_preset("night")
	await d.frames(24)
	await d.cam_swing(f["center"], 38.0, 20.0, 20.0, 14.0, float(f["dist"]) * 0.86, 70, 1, f["aim"])
