## PoiBuilder human sign-off scene: cube + printed checklist.
##
## v0.9.0 round: object mode as its own mode with click-through auto-pick,
## cyan hover / yellow selection language, edge-loop select (alt/double
## click), drag gestures (uniform scale, shift+move extrude, shift+scale
## inset), ops moved to the persistent toolbar, compact auto-hiding overlay
## panel (drag/collapse/pin), and ProBuilder-style drag-to-create with a
## shape-parameter modal.
@tool
extends Node3D


func _enter_tree() -> void:
	# ALWAYS reset to a pristine cube on load: earlier sessions of this scene
	# were mangled by since-fixed bugs, and testing picking/behavior on a
	# deformed mesh produces misleading results.
	if has_node("PBCube"):
		var existing: PBMesh = get_node("PBCube")
		existing.pb_mesh_data = PBMeshData.create_cube(1.0)
	else:
		var cube: PBMesh = PBMesh.create_cube(1.0)
		cube.name = "PBCube"
		add_child(cube)
		cube.owner = get_tree().edited_scene_root if Engine.is_editor_hint() else self
	print("[Phase6] Cube reset to pristine unit cube (expect V=24 F=6 groups=8 edges=12)")


func _ready() -> void:
	print("========== PoiBuilder v0.9.0 human checklist (object mode + gestures + creation) ==========")
	print("Setup: enable the PoiBuilder plugin if needed, select PBCube in the 3D view.")
	print("")
	print("Toolbar (persistent row UNDER the 3D scene toolbar, never inside it):")
	print("  1. A 'PoiBuilder' toolbar row sits BELOW the scene toolbar at all times,")
	print("     even with nothing selected — context buttons grey until a PBMesh is")
	print("     selected. Move/Rotate/Scale | Object/Vertex/Edge/Face | Space | op")
	print("     buttons (Extrude/Inset/Loop Cut/Merge/Subdiv/Weld/Detach/Del) |")
	print("     New Shape + Edit Params | Panel toggle.")
	print("  2. Selecting PBCube enables the row. Ops enable per selection context")
	print("     (e.g. Extrude needs a face selection; Loop Cut an edge; Weld 2+")
	print("     verts) and stay grey otherwise.")
	print("")
	print("Overlay panel (compact readouts + params modal, v0.9.0 redesign):")
	print("  3. The floating panel shows NO op buttons and NO tool/space controls.")
	print("     It auto-hides unless: something is selected (SELECTION row: mode +")
	print("     count), a gizmo drag runs (live Delta/Rotation/Scale/Inset readout),")
	print("     or a params modal is open. Drag it by its header; collapse it with")
	print("     the chevron; pin it with the toolbar 'Panel' toggle.")
	print("")
	print("Mode persistence + OBJECT mode (#9):")
	print("  4. Switch to EDGE (J). Click empty space, click the cube again → back")
	print("     in EDGE mode.")
	print("  5. Click ANOTHER PBMesh while in EDGE mode: the element under the")
	print("     cursor is selected IMMEDIATELY (no transient whole-object gizmo).")
	print("  6. Whole-object transforms: click the toolbar OBJECT button (or re-enter")
	print("     a mesh from nothing) — the stock engine node gizmo appears; H/J/K or")
	print("     the mode buttons return to element editing.")
	print("")
	print("Hover highlights (v0.9.0: hover CYAN, selection YELLOW):")
	print("  7. FACE mode: hovering tints a face translucent CYAN; SELECTED faces")
	print("     are YELLOW. EDGE mode: base wireframe is a thin cyan, hovered edge")
	print("     a thick cyan stroke, selected edges thick YELLOW. VERTEX hover dots")
	print("     are cyan too.")
	print("")
	print("Element picking + loop select (#14):")
	print("  8. Click a face → selects it, gizmo jumps there; shift-click toggles.")
	print("  9. EDGE mode: Alt+click an edge (or double-click it) selects its WHOLE")
	print("     ring (thick yellow); dragging moves the entire loop; a plain click")
	print("     drops back to the single edge.")
	print(" 10. The edge gizmo stays locked to the side you CLICKED from (#6):")
	print("     select an edge from its top face, then hover the same edge from")
	print("     below — the gizmo must NOT flip.")
	print(" 11. H/J/K switch Vertex/Edge/Face; switching mode clears the selection.")
	print("")
	print("Manipulation + gestures (v0.9.0):")
	print(" 12. SCALE is UNIFORM by default (#3): any scale handle scales all axes")
	print("     about the pivot. Shift+scale on edges/verts keeps free (non-uniform)")
	print("     scaling.")
	print(" 13. Shift+Move on a face selection EXTRUDES (#4): at drag start the")
	print("     faces extrude and your drag moves the new caps only. Undo (Ctrl+Z)")
	print("     un-extrudes the whole gesture in one step.")
	print(" 14. Shift+Scale on a face selection INSETS (#5): the drag insets the")
	print("     selected faces uniformly (aspect locked — #13); undo reverts in one")
	print("     step. Escape during the drag restores everything.")
	print(" 15. Regular drags still: welded corners stay welded, Ctrl snaps,")
	print("     Ctrl+Z / Ctrl+Shift+Z undo/redo.")
	print("")
	print("Gizmo orientation space (X key / Space button):")
	print(" 16. Tilt the PBCube NODE ~30°, select a face, cycle X: ELEMENT aligns")
	print("     to the face normal, OBJECT to the node axes, WORLD to world XYZ.")
	print(" 17. While editing, the engine's Q/V/T buttons are disabled; after")
	print("     deselect they work again.")
	print("")
	print("Mesh OPERATIONS (buttons now in the persistent TOOLBAR):")
	print(" 18. Select the cube's top face: the toolbar ops enable; with no")
	print("     selection they are greyed. Extrude/Inset/Subdiv/Del/Detach on")
	print("     faces; Loop Cut on edges; Weld on 2+ verts. Undo/redo per op.")
	print(" 19. Merge on NON-COPLANAR adjacent faces now works (#11): front+top of")
	print("     the cube merge into ONE bent n-gon — it moves as a unit in face")
	print("     mode while its edges/verts stay individually editable; undo")
	print("     restores. Front+back (non-adjacent) still refuses.")
	print(" 20. Detach keeps the source node's TRANSFORM (#10): detach a face from")
	print("     a rotated/translated cube — the new node lands exactly where the")
	print("     face was (same rotation too).")
	print("")
	print("Shape creation (v0.9.0: ProBuilder-style drag creation, #12):")
	print(" 21. Pick any shape from the New Shape menu (works with nothing")
	print("     selected). NOTHING spawns yet — hover faces: they highlight with")
	print("     thick cyan edges + cyan fill.")
	print(" 22. LMB-drag on any surface (floor, a cube's side, on top of an object,")
	print("     or the empty grid): the base rect stays COPLANAR with the surface")
	print("     you pressed; a cyan 3D box wireframe (visible through objects) and")
	print("     the real shaded shape preview grow with the drag.")
	print(" 23. Release the mouse, then move: the shape grows/shrinks along the")
	print("     surface normal (below the surface works too). LMB-click confirms.")
	print("     ESC at any point BEFORE that click cancels with NOTHING created.")
	print(" 24. After the confirming click the overlay opens with the shape's")
	print("     parameters (stairs: Steps; cylinder: Radius/Sides; ...). Changes")
	print("     live-preview. Apply commits (then Ctrl+Z removes the whole shape);")
	print("     Cancel reverts params to the placement values. Either way you land")
	print("     back in builder mode with the shape selected — ready to pick")
	print("     edges/faces/verts.")
	print(" 25. Stairs (and curved stairs) show an ORANGE ARROW at the base")
	print("     pointing at the ascending side while creating.")
	print(" 26. Edit Params: select a freshly created (unmodified) shape — the")
	print("     toolbar button enables; click it, tweak params, Apply/Cancel. After")
	print("     ANY element drag or mesh op on that shape the button greys out")
	print("     (regenerating would destroy the edits).")
	print("")
	print("Misc:")
	print(" 27. The editor manipulator gizmo is half size by default (PoiBuilder")
	print("     sets EditorSettings > Editors > 3D > Manipulator Gizmo Size 80→40")
	print("     on first load; your own customization is respected).")
	print(" 28. Negative checks: clicking/dragging empty space never moves meshes;")
	print("     only one gizmo is ever visible; VERTEX drags move the whole welded")
	print("     corner; faces stay quads — no triangulation diagonals.")
	print("=============================================================================")
